### ISSUE TITLE
fused_modulate= False model convert increase

### ISSUE THREAD

**Issue by goodclass** [genforce/genforce#16]
hi

我嘗試把stylegan2模型轉換coreml。由於轉換工具本身存在缺陷，無法使用參數作為權值。然後修改`fused_modulate=false`後可以通過，但出現一個問題。就是轉換之後模型變大了。
torch 121M，script 168M，coreml 218M
我現在水准暫時無法看懂，參數設置後為什麼會增長。

```py
latent_codes = np.random.randn(1,18,512).astype(np.float32)
dummy_input = torch.from_numpy(latent_codes)

torch_model = StyleGAN2Generator(fused_modulate=False)

traced_model = torch.jit.trace(torch_model.net.synthesis, dummy_input)
torch.jit.save(traced_model, './mobile.pt')

model = ct.convert( traced_model, inputs=[ct.TensorType(name="input_1", shape=latent_codes.shape)],)
model.save('./stylegan2.mlmodel')
```

![image](https://raw.githubusercontent.com/goodclass/PythonAI/master/image/style2.png)

**Comment by limbo0000** [comment]
Hi @goodclass, it seems that 'ct' leads to the inconsistency of #params.  Sorry about that we could not provide such support for such tool due to the lack of corresponding experience. Maybe you could find whether 'ct' leads to similar situations on other models.   

I would close this issue since the major concern is about 'ct' which is beyond our codebase. You could re-open it if you have any other comments.

**Comment by goodclass** [comment]
Sorry.  CT is a conversion tool of apple, coremltools.
This enables the model to run on this iPhone. Although I have implemented it, the coreml model is much more effective.
```py
import coremltools as ct
```
This is not an urgent issue right now. I also have a fatal memory problem to deal with.
Thank you for the stylegan2 model. It's an elegant person in GitHub
